# Generated by Django 3.2.9 on 2021-12-06 12:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_date',
        ),
        migrations.AddField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
