# Generated by Django 3.2.9 on 2021-12-06 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211206_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
